baseurl = "https://www.felixwang.io/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
title = "Felix Wang"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Hi,I'm Felix"
subtitle = "a new developer"
logo = "https://res.cloudinary.com/dfynefyys/image/upload/v1539523433/personal%20website/logo/logoko.png"
favicon = "https://res.cloudinary.com/dfynefyys/image/upload/v1539523433/personal%20website/logo/logoko.png"
share_img = "https://res.cloudinary.com/dfynefyys/image/upload/v1539619299/personal%20website/bigimg/%E4%B8%AA%E4%BA%BA%E5%9B%BE%E7%89%87.jpg"
dateFormat = "January 2, 2006"
commit = false
rss = true
baiduKey = "06304fbb932f882f56d5ef0dba136201"
#comments = false
#sharebutton = true
algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "王呈飞的博客|a new developer|felixwang.io"
errorpage = "https://res.cloudinary.com/dfynefyys/image/upload/v1540917312/personal%20website/bigimg/%E5%BE%AE%E4%BF%A1%E5%8F%B7_%E5%89%AF%E6%9C%AC.jpg"


[[Params.bigimg]]
src = "https://res.cloudinary.com/dfynefyys/image/upload/v1539619803/personal%20website/bigimg/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%A4%A7%E5%9B%BE1.jpg"
desc = ""

[[Params.bigimg]]
src = "https://res.cloudinary.com/dfynefyys/image/upload/v1539619813/personal%20website/bigimg/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%A4%A7%E5%9B%BE2.jpg"
desc = ""

[[Params.bigimg]]
src = "https://res.cloudinary.com/dfynefyys/image/upload/v1539619817/personal%20website/bigimg/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%A4%A7%E5%9B%BE3.gif"
desc = ""

[[Params.bigimg]]
src = "https://res.cloudinary.com/dfynefyys/image/upload/v1539619826/personal%20website/bigimg/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%A4%A7%E5%9B%BE4.jpg"
desc = ""

[Author]
  name = "Felix Wang(王呈飞)"
  website = "http://www.felixwang.io"
  #email = "wcfgg@foxmail.com"
  #facebook = "felixwang"
  #googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "sougg"
  #twitter = "felixwang"
  linkedin = "wangchengfei"
  #500px = "felixwang"
  #medium = "felixwang"
  #instagram = "felixwang"
  weibo = "掏炭的男人"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "statistics"
    url = "categories/statistics"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "java"
    url = "categories/java"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "capriccio"
    url = "categories/capriccio"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "notes"
    url = "categories/notes"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "algorithm"
    url = "categories/math&algorithm"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 7


[[menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 3

[[menu.main]]
    parent = "Gitbooks"
    name = "Envoy proxy中文文档"
    url = "https://servicemesher.github.io/envoy"
    weight = 4

[[menu.main]]
    parent = "Gitbooks"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 5

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "k8s all-in-one"
    url = "https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "Spark on kubernetes"
    url = "spark-on-k8s"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "sofa-mesh"
    url = "https://github.com/alipay/sofa-mesh"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "sofa-mosn"
    url = "https://github.com/alipay/sofa-mosn"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Beautifulhugo"
    url = "https://github.com/rootsongjc/beautifulhugo"
    weight = 5


#[[menu.main]]
#    name = "About"
#    url = "about"
#    weight = 5